const config = {
  APP_NAME: "VLs-VietLabs",
  LOCAL_LANGUAGE_LABEL: import.meta.env.VITE_LOCAL_LANGUAGE_LABEL,
  BASE_URL: import.meta.env.VITE_BASE_URL,
  LOCAL_PROFILE: "VLs_PROFILE",
  LOCAL_AUTHENTICATED: "VLs_AUTHENTICATED",
  LOCAL_ACCESS_TOKEN: "VLs_ACCESS_TOKEN",
  LOCAL_REFRESH_TOKEN: "VLs_REFRESH_TOKEN",
  LOCAL_LOGIN_TYPE: "VLs_LOGIN_TYPE",
  LOCAL_USERNAME: "VLs_USERNAME",
  TIMEOUT: 50000,
  PAGE_SIZE: 500,
  TENANT_URL: "https://htpa.sharepoint.com",
  LAST_VERSION: "2025-08-30 18:00",
  IN_TEST: import.meta.env.VITE_IN_TEST === "Yes",
  HOME_PAGE: import.meta.env.VITE_HOME_PAGE,
  IGNORE_MAIL: false,
};

export default config;